# Generated by Django 4.2.1 on 2023-05-26 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_remove_postcategory_subscribers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='subscribers',
        ),
    ]
